version: "3"

services:
  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_DATABASE=testdb
    ports:
      - "27017:27017"
    networks:
      - stack

networks:
  stack: {}
